- .php_cs
- README.md
- config/prooph_service_bus.config.php
- docs/factories.md
- src/Factory/AbstractBusFactory.php
- src/Factory/CommandBusFactory.php
- src/Factory/EventBusFactory.php
- src/Factory/QueryBusFactory.php
- tests/Factory/BusFactoriesTest.php
This PR is not completed yet. 
Missing parts:
> Provide container-aware factories

- README.md
- docs/async_message_producer.md
- src/Async/MessageProducer.php
See prooph/psb-bernard-producer#1
> Add async message producer interface

- composer.json
- src/Container/AbstractBusFactory.php
- src/Container/CommandBusFactory.php
- src/Container/EventBusFactory.php
- src/Container/QueryBusFactory.php
- tests/Container/BusFactoriesTest.php
Interop-Config library reduces the boilerplate code of the factories.
> Implemented Interop Config Library

- docs/message_bus.md
- src/CommandBus.php
- src/EventBus.php
- src/MessageBus.php
- src/Plugin/InvokeStrategy/AbstractInvokeStrategy.php
- src/Plugin/InvokeStrategy/FinderInvokeStrategy.php
- src/QueryBus.php
- tests/CommandBusTest.php
- tests/Container/BusFactoriesTest.php
- tests/EventBusTest.php
- tests/Plugin/InvokeStrategy/AbstractInvokeStrategyTest.php
- tests/Plugin/InvokeStrategy/FinderInvokeStrategyTest.php
- tests/QueryBusTest.php
See #87 
A new event param was added `message-handled` which is initialized with `false` and set to true by all invoke strategies (incl. closures) after message was handled. 
The command and query bus check the param after triggering `invoke-handler` / `invoke-finder` and throw an exception if param was not set to `true`.
> Check param message-handled and throw ex in false case

- .gitignore
- README.md
- composer.json
- docs/bookdown.json
I've added the bookdown.io documentation and there are some issues:
1. Some links (license, composer.json, ...) are broken because they are not absolut
2. It is possible to not include the bookdown templates in require-dev, but the default template looks not pretty much. I don't know if users generates the docs by yourself if we provide online docs for gh-pages and link to them in the readme.md file.
3. I did not change the doc structure for BC but I think this is the best way
What do you think?
> added bookdown.io documentation

- src/Plugin/InvokeStrategy/OnEventStrategy.php
- tests/Mock/CustomMessageWithName.php
- tests/Plugin/InvokeStrategy/OnEventStrategyTest.php
This change fixes an issue with `OnEventStrategy` not correctly
determining the event name if a custom event returns a message name
other than its own class name through the `messageName()` method.
> Resolve #107 - Correctly detect event name in OnEventStrategy

- src/CommandBus.php
Sorry PHP Storm keeps telling me I'm not annotating or catching `\Exception` when I don't need to.
> Exceptions are all wrapped from the command bus.

- composer.json
- config/services.php
- src/Container/AbstractBusFactory.php
- src/Container/CommandBusFactory.php
- src/Container/EventBusFactory.php
- src/Container/QueryBusFactory.php
- tests/Container/BusFactoriesTest.php
This PR adds support for interop-config 1.0 and adds a new feature called *static factories*. Also dependencies are updated to latest versions and Composer scripts were added.
If this is ok, I will update the other packages in the same manner. /cc @codeliner 
**Note:** We have some BC breaks of the factory methods because the interface of interop-config has changed. I think we should also mark the factories as final, because the config id (container id) is now configurable. What do you think?
> update factories to interop-config 1.0, add static factory support

- src/Container/CommandBusFactory.php
- src/Container/EventBusFactory.php
- src/Container/QueryBusFactory.php
> mark factories as final

- src/Plugin/Router/EventRouter.php
- src/Plugin/Router/MessageBusRouterPlugin.php
- src/Plugin/Router/RegexRouter.php
- src/Plugin/Router/SingleHandlerRouter.php
- tests/CommandBusTest.php
- tests/Container/BusFactoriesTest.php
- tests/Plugin/Router/EventRouterTest.php
- tests/Plugin/Router/RegexRouterTest.php
- RegexRouter::onRoute marked as deprecated
- EventRouter::onRouteEvent marked as deprecated
> Add MessageBusRouterPlugin interface

- config/prooph_service_bus.config.php
- src/Container/AbstractBusFactory.php
- tests/Container/BusFactoriesTest.php
- tests/Mock/NoopMessageProducer.php
@prolic can you take over the release when everything is merged to develop?
Won't have much time the next days and then I'm off for 3 weeks. 
/cc @guyradford
> bus factory async option

- src/MessageBus.php
- src/QueryBus.php
- tests/QueryBusTest.php
This PR provides a bugfix for not resettable exceptions with finalize event.
/cc @prolic please confirm this as a bug
> Bugfix: exception is not resettable with finalize event

- src/Plugin/InvokeStrategy/FinderInvokeStrategy.php
- src/Plugin/InvokeStrategy/HandleCommandStrategy.php
- src/Plugin/InvokeStrategy/OnEventStrategy.php
- tests/Mock/CustomInvokableMessageHandler.php
- tests/Plugin/InvokeStrategy/FinderInvokeStrategyTest.php
- tests/Plugin/InvokeStrategy/HandleCommandStrategyTest.php
- tests/Plugin/InvokeStrategy/OnEventStrategyTest.php
See https://github.com/prooph/service-bus/issues/156
There was no check in the InvokeStrategy if a message was already handled
> Do not process already process messages with a custom strategy

- src/Plugin/ServiceLocatorPlugin.php
- tests/Plugin/ServiceLocatorPluginTest.php
ServiceLocator does not correctly merge new listeners to list of known listeners
https://3v4l.org/ZbsuF
array_merge will" "If, however, the arrays contain numeric keys, the later value will not overwrite the original value, but will be appended"
> avoid array_merge due to appending

- src/Async/AsyncMessage.php
- tests/Container/BusFactoriesTest.php
`AsyncMessage` should extend the `Message` interface as it's API is expected inside of `AsyncSwitchMessageRouter`.
We're upgrading our system to use async messaging but we don't use the `DomainMessage` but we did implement `AsyncMessage` and the system fell over because we were unaware we had to implement this API.
> AsyncMessage now implements the Message interface

- docs/message_bus.md
- src/EventBus.php
- src/Exception/EventListenerException.php
- src/Plugin/ListenerExceptionCollectionMode.php
- tests/EventBusTest.php
- tests/Mock/AutoErrorProducer.php
- tests/Plugin/ListenerExceptionCollectionModeTest.php
Fixes #165 
To keep BC with current message bus behavior I've added a "listener exception collection" mode to the event bus. This mode can be enabled via plugin or by extending the event bus class and overriding `EventBus::$collectExceptions` property.
My first idea was to add a config option but all three buses use the same abstract factory and I don't want to change that. IMHO the plugin achieves the same goal.
> Optionally collect listener exceptions

- src/CommandBus.php
We ran into trouble with command bus v5. As this version supports PHP 5.x we don't catch `\Throwable`, which is ok in most situations except the one I fixed in this PR.
Problem: 5.x command bus is used in a long-running script. We have a try catch (\Throwable $ex) around command bus dispatch and are able to handle the \Throwable without killing the script. The problem is that the command bus still thinks that it is in dispatching mode, because this mode is only turned off in case of an \Exception.
The idea here is to only fix that situation and don't refactor the old version of service-bus to support \Throwable all the way down. In v6 we catch \Throwable and people (including our project) should upgrade.
> Catch throwable and reset isDispatching

- src/EventBus.php
- src/Plugin/InvokeStrategy/OnEventStrategy.php
- tests/EventBusTest.php
- tests/Mock/CustomMessageEventHandler2.php
- tests/Mock/CustomMessageEventHandlerThrowingExceptions.php
- tests/Mock/CustomOnEventStrategy.php
- tests/Plugin/InvokeStrategy/OnEventStrategyTest.php
resolves https://github.com/prooph/service-bus/issues/169
see also https://youtu.be/U01EVU7LTqY
and part2 is here: https://youtu.be/KYQiy_WiyaM
> Fix Bugs in Event Bus

- src/Plugin/Guard/FinalizeGuard.php
- tests/Plugin/Guard/FinalizeGuardTest.php
resolves https://github.com/prooph/service-bus/issues/177
> fix FinalizeGuard

- README.md
6.x releases are all instructing to install 5.x. Using `composer require` removes the necessity of updating the documentation on every release.
> Update outdated install instructions

- README.md
- docs/async_message_producer.md
- docs/plugins.md
- docs/service_bus_system.md
While reading the documentation about Async Message Producer I was very confused by "PBS". I searched websites like abbreviations.com for several minutes before I realized the intended meaning. I suggest to remove this abbreviation to avoid confusion.
I'm not sure if you prefer "Prooph Service Bus" or "ProophServiceBus". For example prooph/event-store docs use "Prooph Event Store" while docs in other packages are using "ProophEventStore".
> Remove abbreviation

- src/Plugin/Router/AsyncSwitchMessageRouter.php
- tests/Plugin/Router/AsyncSwitchMessageRouterTest.php
Not that I'm using any other bus implementation but I was reading the code of `AsyncSwitchMessageRouter` and the assumption of the bus being EventBus doesn't seem correct.
It might be better to split this plugin to two instead but that would be BC break.
> Add exception
